### ISSUE TITLE
Allowed files

### ISSUE THREAD

**Issue by SimpleHomeUser** [Oros42/tiny_DnDUp#2]
Hello Oros

First thank you for this script, it is usefull.
I can't upload anything else than images.
I tried to add things in the config.php but I am useless in programming:
I added: $allowed_file_types=array('image/png', 'image/jpeg', 'image/gif','application/xlsx')
or 
'application/vnd.ms-excel');

but that doesn't work.
What shall I write to allow any file ?

Thank you

**Comment by Oros42** [comment]
Hello
Thank you for this question.
I have made a fix for allowed all types of file if you want. And if the file is not allowed, it show you is type in a alert message.

**Comment by SimpleHomeUser** [comment]
Thank you very much for your quick reply.

With the modification ($allowed_file_types=null;) the files appear in the drop zone but they never get uploaded.
(I tried to launch the developer tools in Firefox but I have no idea what to look for)

**Comment by Oros42** [comment]
Oups for the «!», line 95 : !empty($allowed_file_types)
