### ISSUE TITLE
Creation .htaccess

### ISSUE THREAD

**Issue by SimpleHomeUser** [Oros42/tiny_DnDUp#3]
Bonjour,

Le fichier .htaccess qui est créé dans les répertoires d'upload sont des fichiers vide.

Dans l'index.php ligne 77 tu mets : $htaccess_content
je pense que tu veux mettre $default_htaccess comme la valeur dans le config.php ?

Merci encore pour ce script super pratique (surtout depuis qu'on peut l'utiliser depuis un téléphone).

**Comment by Oros42** [comment]
Je te remercie d'avoir remonté ce point. Je corrige ça ;-)
